test_that("record_type_from_int handles all known ranges", {
    expect_equal(record_type_from_int(100), "RegularTimeSeries")
    expect_equal(record_type_from_int(102), "RegularTimeSeriesProfile")
    expect_equal(record_type_from_int(107), "RegularTimeSeriesProfile")
    expect_equal(record_type_from_int(105), "RegularTimeSeries")
    expect_equal(record_type_from_int(110), "IrregularTimeSeries")
    expect_equal(record_type_from_int(199), "IrregularTimeSeries")
    expect_equal(record_type_from_int(200), "PairedData")
    expect_equal(record_type_from_int(300), "Text")
    expect_equal(record_type_from_int(400), "Grid")
    expect_equal(record_type_from_int(450), "Tin")
    expect_equal(record_type_from_int(20),  "LocationInfo")
    expect_equal(record_type_from_int(91),  "Array")
    expect_equal(record_type_from_int(99999), "Unknown")
    expect_equal(record_type_from_int(NA),    "Unknown")
})
